### ISSUE TITLE
Recommend removing "Unworkable" statement

### ISSUE THREAD

**Issue by seelder** [SoftwareEngineeringToolDemos/ICSE-2013-V-ISSUE-LIZER#4]
The statement "This tool was certified as Unworkable for this project because when I tried building the tool from the source code, it hit various dependency issues which could not be resolved. Also neither the executable nor the dataset required for it was available on the Internet." is unnecessary and confusing. It took me a minute to realize what you were talking about when you said that the executable and the dataset were unavailable since so much appears to be available. When you say "various dependency issues which could not be resolved", I am curious what dependencies it has, what those issues were, etc. I checked with Professor Emerson and it is not necessary to explain why a tool is unworkable. I recommend removing the whole statement.

**Comment by gsrajadh** [comment]
But I need mention that the tool is unworkable,right? Also please follow this instead of making the changes in the original Readme.md:
"If you intend to fix an issue that you report, assign that issue to yourself. Then, fix the issue using a pull request (do not fix the problem directly by, say, editing the readme). Be sure to close the corresponding issue in your commit message. When the tool owner receives your pull request, they will decide whether to accept it."

**Comment by seelder** [comment]
I reverted this change. Do you agree with issue #1 ? I made a mistake while reverting, but if you agree with the change I won't undo it and will re-commit this change. If I need to revert both of them let me know and I can keep looking for a solution.

Relating to this, in the instructor's response to "Unworkable Tool Issues" he states "The readme shouldn't indicate whether the tool is workable or not."
